-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 12:06:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`cleint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`cleint` (
  `ID_client` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(45) NULL,
  `adreça` VARCHAR(45) NULL,
  `codiPostal` VARCHAR(45) NULL,
  `localitat` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `telefon` INT NULL,
  PRIMARY KEY (`ID_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `ID_botiga` INT NOT NULL,
  `adreça` VARCHAR(45) NULL,
  `codiPostal` INT NULL,
  `localitat` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_botiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleat` (
  `ID_empleat` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `ID_botiga` INT NOT NULL,
  PRIMARY KEY (`ID_empleat`),
  INDEX `fk_empleat_botiga1_idx` (`ID_botiga` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`ID_botiga`)
    REFERENCES `pizzeria`.`botiga` (`ID_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `ID_comanda` INT NOT NULL,
  `data` DATETIME NULL,
  `tipusComanda` VARCHAR(45) NULL,
  `quantitat` INT NULL,
  `preu` FLOAT NULL,
  `ID_client` INT NOT NULL,
  `ID_botiga` INT NOT NULL,
  `ID_empleat` INT NOT NULL,
  PRIMARY KEY (`ID_comanda`),
  INDEX `fk_comanda_cleint_idx` (`ID_client` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`ID_botiga` ASC) VISIBLE,
  INDEX `fk_comanda_empleat1_idx` (`ID_empleat` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_cleint`
    FOREIGN KEY (`ID_client`)
    REFERENCES `pizzeria`.`cleint` (`ID_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`ID_botiga`)
    REFERENCES `pizzeria`.`botiga` (`ID_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_empleat1`
    FOREIGN KEY (`ID_empleat`)
    REFERENCES `pizzeria`.`empleat` (`ID_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizzaCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizzaCategoria` (
  `ID_pizzaCategoria` INT NOT NULL,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_pizzaCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producte` (
  `ID_producte` INT NOT NULL,
  `producteKind` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `descripcio` VARCHAR(256) NULL,
  `img` VARCHAR(45) NULL,
  `preu` FLOAT NULL,
  `ID_pizzaCategoria` INT NOT NULL,
  PRIMARY KEY (`ID_producte`),
  INDEX `fk_producte_pizzaCategoria1_idx` (`ID_pizzaCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producte_pizzaCategoria1`
    FOREIGN KEY (`ID_pizzaCategoria`)
    REFERENCES `pizzeria`.`pizzaCategoria` (`ID_pizzaCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`descipcioComanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`descipcioComanda` (
  `ID_descipcioComanda` INT NOT NULL,
  `quantitat` INT NULL,
  `preu` FLOAT NULL,
  `ID_comanda` INT NOT NULL,
  `ID_producte` INT NOT NULL,
  PRIMARY KEY (`ID_descipcioComanda`),
  INDEX `fk_descipcioComanda_comanda1_idx` (`ID_comanda` ASC) VISIBLE,
  INDEX `fk_descipcioComanda_producte1_idx` (`ID_producte` ASC) VISIBLE,
  CONSTRAINT `fk_descipcioComanda_comanda1`
    FOREIGN KEY (`ID_comanda`)
    REFERENCES `pizzeria`.`comanda` (`ID_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_descipcioComanda_producte1`
    FOREIGN KEY (`ID_producte`)
    REFERENCES `pizzeria`.`producte` (`ID_producte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
