select nombre from producto;
select nombre, precio from producto;
select * from producto;
alter table producto add column dolars double; update producto set dolars = precio * 1.06; select * FROM producto;
alter table producto rename column precio to euros;
update producto set nombre = upper(nombre);
update producto set nombre =lower(nombre);
select nombre, left(upper(nombre), 2)as fabriccante from tienda.fabricante;
select nombre, round(euros) from tienda.producto;
select nombre, truncate(euros, 0) from tienda.producto;
select p.codigo_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo; 
select distinct codigo_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo; 
select nombre from fabricante order by nombre;
select nombre from fabricante order by nombre desc;
select nombre, euros from producto order by nombre, euros desc;
select * from fabricante limit 5;
select * from fabricante limit 3, 2;
select nombre, euros from producto order by euros limit 1;
select nombre, euros from producto order by euros desc limit 1;
select nombre, codigo_fabricante from producto p where p.codigo_fabricante = 2;
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo order by f.nombre;
select p.codigo, p.nombre, p.codigo_fabricante, f.nombre from producto p inner join fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo order by p.euros limit 1;
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f where p.codigo_fabricante = f.codigo order by p.euros desc limit 1;
select p.codigo, p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre ='Lenovo';
select p.codigo, p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre ='Crucial' and p.euros > 200;
select p.codigo, p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre ='Asus' or f.nombre ='Hewlett-Packard' or f.nombre ='Seagate';
select p.codigo, p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre in ('Asus','Hewlett-Packard','Seagate');
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where right(f.nombre, 1) = 'e';
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre like '%w%';
select p.nombre, p.euros, f.nombre as nombre_fabricante from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where p.euros >= 180 order by p.euros desc , p.nombre;
select distinct f.codigo, f.nombre from fabricante f inner join producto p where f.codigo = p.codigo_fabricante;
select f.codigo, f.nombre, p.nombre as producto_nombre from fabricante f left join producto p on f.codigo = p.codigo_fabricante;
select * from fabricante f where f.codigo not in (select distinct producto.codigo_fabricante from producto);
select * from producto p where p.codigo_fabricante in (select f.codigo from fabricante f where f.nombre = 'Lenovo');
select p.nombre, p.euros from producto p where p.euros = (select p.euros from producto where p.codigo_fabricante = (select f.codigo from fabricante f where f.nombre = 'Lenovo') order by p.euros desc limit 1);
select p.nombre from producto p inner join fabricante f where f.nombre = 'Lenovo' order by p.euros desc limit 1;
select p.nombre from producto p inner join fabricante f where f.nombre = 'Hewlett-Packard' order by p.euros limit 1;
select * from producto p where p.euros >= (select p.euros from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Lenovo' order by p.euros desc limit 1);
select * from producto p inner join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Asus' and p.euros > (select sum(p.euros) / count(p.euros) from producto);
-- -----------
-- universitat
-- -----------
select p.nombre, p.apellido1, p.apellido2, p.fecha_nacimiento from persona p where p.tipo = 'alumno' order by p.fecha_nacimiento desc;
select p.nombre, p.apellido1, p.apellido2, p.telefono from persona p where p.tipo = 'alumno' and p.telefono is null;
select p.nombre, p.apellido1, p.apellido2, p.fecha_nacimiento from persona p where p.tipo = 'alumno' and year(p.fecha_nacimiento) = 1999;
select p.nombre, p.apellido1, p.apellido2, p.nif from persona p where p.tipo = 'profesor' and p.telefono is null and p.nif like '%k';
select a.nombre from asignatura a where cuatrimestre = 1 and curso = 3 and id_grado = 7;
select pers.apellido1, pers.apellido2, pers.nombre, departamento.nombre as departamento from persona pers inner join profesor pro on pers.id = pro.id_profesor inner join departamento on pro.id_departamento = departamento.id where pers.tipo = 'profesor' order by pers.apellido1, pers.apellido2, pers.nombre;
select asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin from asignatura inner join alumno_se_matricula_asignatura on asignatura.id = alumno_se_matricula_asignatura.id_asignatura inner join curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id inner join persona on persona.id = alumno_se_matricula_asignatura.id_alumno where persona.nif = '26902806M';
select distinct departamento.nombre from departamento inner join profesor on departamento.id = profesor.id_departamento inner join asignatura on profesor.id_profesor = asignatura.id_profesor inner join grado on asignatura.id_grado = grado.id  where grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
select distinct * from persona  inner join alumno_se_matricula_asignatura  on persona.id = alumno_se_matricula_asignatura.id_alumno  inner join curso_escolar  on curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar where curso_escolar.anyo_inicio = '2018' and curso_escolar.anyo_fin = '2019';
select departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre from persona left join profesor on persona.id = profesor.id_profesor left join departamento on profesor.id_departamento = departamento.id where persona.tipo = 'profesor' order by departamento.nombre, persona.apellido1, persona.nombre; 
select distinct persona.nombre, persona.apellido1 from persona left join profesor on persona.id = profesor.id_profesor left join departamento on departamento.id = profesor.id_departamento where persona.tipo = 'profesor' and departamento.id is null;
select distinct departamento.nombre from departamento left join profesor on departamento.id = profesor.id_departamento left join persona on persona.id = profesor.id_profesor where persona.nombre is null;
select distinct persona.nombre, persona.apellido1 from persona left join profesor on profesor.id_profesor = persona.id left join asignatura on asignatura.id_profesor = profesor.id_profesor where persona.tipo = 'profesor' and asignatura.id_profesor is null;
select distinct asignatura.nombre from asignatura where asignatura.id_profesor is null;
select distinct departamento.nombre from departamento left join profesor on profesor.id_departamento = departamento.id left join asignatura on asignatura.id_profesor = profesor.id_profesor left join alumno_se_matricula_asignatura on asignatura.id = alumno_se_matricula_asignatura.id_asignatura left join curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id where asignatura.id_profesor is null;

select count(id) as alumnes_total from persona where tipo = 'alumno';
select count(id) as alumnes_total from persona where tipo = 'alumno' and year(persona.fecha_nacimiento) = 1999;
select departamento.nombre, count(persona.id) as numero_profes from persona inner join profesor on persona.id = profesor.id_profesor inner join departamento on profesor.id_departamento = departamento.id where persona.tipo = 'profesor' group by departamento.nombre order by numero_profes desc;
select departamento.nombre, count(persona.id) as numero_profes from departamento left join profesor on departamento.id = profesor.id_departamento left join persona on persona.id = profesor.id_profesor where (persona.nombre is null) or (persona.tipo = 'profesor') group by departamento.nombre order by numero_profes desc;
select grado.nombre, count(asignatura.id) as asignaturas_asociadas from grado left join asignatura on grado.id = asignatura.id_grado group by grado.nombre order by asignaturas_asociadas desc;
select asignaturaConsulta.nombre, asignaturas_asociadas from (select grado.nombre, count(asignatura.id) asignaturas_asociadas from grado left join asignatura on grado.id = asignatura.id_grado group by grado.nombre  order by asignaturas_asociadas desc) as asignaturaConsulta where asignaturas_asociadas > 40;
select grado.nombre, asignatura.tipo, sum(creditos) as creditos_totales from asignatura inner join grado on asignatura.id_grado = grado.id group by asignatura.tipo, asignatura.id_grado;
select curso_escolar.anyo_inicio, count(alumno_se_matricula_asignatura.id_alumno) as alumnos_matriculados from alumno_se_matricula_asignatura inner join curso_escolar on alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id group by alumno_se_matricula_asignatura.id_curso_escolar;
select profesor.id_profesor, persona.nombre, persona.apellido1, persona.apellido2, count(asignatura.id) as asignaturas from profesor left join asignatura on asignatura.id_profesor = profesor.id_profesor inner join persona on profesor.id_profesor = persona.id group by profesor.id_profesor order by asignaturas desc;
select * from persona where fecha_nacimiento = (select max(fecha_nacimiento) from persona where tipo = 'alumno');
