-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 11:55:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Proveidor` (
  `ID_proveidor` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `adreça` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `pis` INT NULL,
  `porta` INT NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `pais` VARCHAR(45) NULL,
  `fax` INT NULL,
  `NIF` VARCHAR(45) NULL,
  `telefon` INT NULL,
  PRIMARY KEY (`ID_proveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Ulleres` (
  `ID_ulleres` INT NOT NULL,
  `ID_proveidor` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `graduacioEsquerre` FLOAT NULL,
  `graduacioDreta` FLOAT NULL,
  `muntura` VARCHAR(45) NULL,
  `colorVidreEsquerre` VARCHAR(45) NULL,
  `colorVidreDret` VARCHAR(45) NULL,
  `preu` FLOAT NULL,
  PRIMARY KEY (`ID_ulleres`),
  INDEX `fk_Ulleres_Proveidor_idx` (`ID_proveidor` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Proveidor`
    FOREIGN KEY (`ID_proveidor`)
    REFERENCES `optica`.`Proveidor` (`ID_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Empleat` (
  `ID_empelat` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_empelat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Client` (
  `ID_client` INT NOT NULL,
  `adreça` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `correu` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Vendes` (
  `ID_vendes` INT NULL,
  `ID_ulleres` INT NULL,
  `Empleat_ID_empelat` INT NULL,
  `ID_client` INT NULL,
  `data_venda` DATE NULL,
  PRIMARY KEY (`ID_vendes`),
  INDEX `fk_Vendes_Ulleres1_idx` (`ID_ulleres` ASC) VISIBLE,
  INDEX `fk_Vendes_Empleat1_idx` (`Empleat_ID_empelat` ASC) VISIBLE,
  INDEX `fk_Vendes_Client1_idx` (`ID_client` ASC) VISIBLE,
  CONSTRAINT `fk_Vendes_Ulleres1`
    FOREIGN KEY (`ID_ulleres`)
    REFERENCES `optica`.`Ulleres` (`ID_ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Empleat1`
    FOREIGN KEY (`Empleat_ID_empelat`)
    REFERENCES `optica`.`Empleat` (`ID_empelat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Client1`
    FOREIGN KEY (`ID_client`)
    REFERENCES `optica`.`Client` (`ID_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
